/**
 * SQL Server → Postgres schema translation (GUIDED-MIGRATION.md §7b, the larger second `guided`
 * heart; HETEROGENEOUS.md §6). Drafts target Postgres DDL from the SQL Server catalog and surfaces
 * the type decisions that need a human. NEVER auto-applies: the caller writes the draft for review
 * and cutover gates on sign-off (§9 caveat 1 — schema translation cannot be fully automated).
 *
 * Pure (no IO): the type matrix + DDL rendering are unit-tested; the live drafter
 * (`draftTargetSchemaSqlServer`) just feeds catalog rows in. The DDL render + decision-collection
 * are shared with the MySQL translator (`renderCreateTableFromColumns`).
 *
 * Beyond MySQL's matrix, SQL Server adds: a wider fractional-second range (datetime2/time/
 * datetimeoffset go to 7, but Postgres caps at 6 — flagged with precision-loss), IDENTITY columns,
 * computed columns, MONEY/SMALLMONEY, UNIQUEIDENTIFIER→uuid, and the ROWVERSION trap (SQL Server's
 * `timestamp` type is an 8-byte binary version stamp, NOT a datetime). Anything unsettleable is
 * drafted to a safe default and flagged for review rather than silently guessed.
 */

import {
  renderCreateTableFromColumns,
  type SchemaDraft,
  type TableDraft,
  type TranslatedColumn,
} from "./schema-translate.ts";
import type { SqlServerConn } from "./sqlserver.ts";

/** A row of the SQL Server catalog (INFORMATION_SCHEMA.COLUMNS + COLUMNPROPERTY flags) we read. */
export interface SqlServerColumn {
  COLUMN_NAME: string;
  DATA_TYPE: string; // e.g. "int", "varchar", "datetime2", "uniqueidentifier", "money"
  IS_NULLABLE: string; // "YES" | "NO"
  CHARACTER_MAXIMUM_LENGTH: number | string | null; // -1 = MAX
  NUMERIC_PRECISION: number | string | null;
  NUMERIC_SCALE: number | string | null;
  DATETIME_PRECISION: number | string | null;
  /** COLUMNPROPERTY(..., 'IsIdentity') — 1 for an IDENTITY column. */
  IS_IDENTITY?: number | string | null;
  /** COLUMNPROPERTY(..., 'IsComputed') — 1 for a computed column. */
  IS_COMPUTED?: number | string | null;
}

const num = (v: number | string | null | undefined, fallback: number): number => {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
};

const truthy = (v: number | string | null | undefined): boolean => v === 1 || v === "1";

/** Postgres caps fractional-second precision at 6; SQL Server datetime2/time/offset go to 7. */
function tsPrecision(col: SqlServerColumn): { p: number; review?: string } {
  const p = num(col.DATETIME_PRECISION, 0);
  if (p > 6)
    return {
      p: 6,
      review: `fractional-second precision ${p} exceeds Postgres max 6 — truncated to 6`,
    };
  return { p };
}

const withP = (base: string, p: number): string => (p > 0 ? `${base}(${p})` : base);

/** Translate one SQL Server column to its Postgres type, flagging decisions a human must ratify. */
export function translateColumn(col: SqlServerColumn): TranslatedColumn {
  const base = mapType(col);
  const notes: string[] = base.review ? [base.review] : [];

  if (truthy(col.IS_COMPUTED)) {
    notes.push(
      "COMPUTED column: drafted as a plain column so the CDC sink can write captured values; " +
        "convert to a Postgres `GENERATED ALWAYS AS (...) STORED` only after translating the " +
        "expression by hand (T-SQL functions ≠ Postgres)",
    );
  } else if (truthy(col.IS_IDENTITY)) {
    notes.push(
      "IDENTITY column: drafted as a plain column so the CDC sink can write captured values; " +
        "consider `GENERATED BY DEFAULT AS IDENTITY` — cutover resyncs the sequence to MAX(pk)",
    );
  }

  return notes.length > 0 ? { ...base, review: notes.join("; ") } : base;
}

/** The raw type → Postgres type matrix, before the identity/computed overlay. */
function mapType(col: SqlServerColumn): TranslatedColumn {
  const dt = col.DATA_TYPE.toLowerCase();
  const nullable = col.IS_NULLABLE.toUpperCase() === "YES";
  const maxLen = num(col.CHARACTER_MAXIMUM_LENGTH, 0); // -1 = MAX
  const out = (pgType: string, review?: string): TranslatedColumn => ({
    name: col.COLUMN_NAME,
    pgType,
    nullable,
    ...(review ? { review } : {}),
  });

  switch (dt) {
    case "tinyint":
      return out("smallint"); // SQL Server TINYINT is 0–255 unsigned; smallint holds it cleanly
    case "smallint":
      return out("smallint");
    case "int":
      return out("integer");
    case "bigint":
      return out("bigint");
    case "bit":
      return out("boolean");
    case "decimal":
    case "numeric":
      return out(`numeric(${num(col.NUMERIC_PRECISION, 38)},${num(col.NUMERIC_SCALE, 0)})`);
    case "money":
      return out("numeric(19,4)");
    case "smallmoney":
      return out("numeric(10,4)");
    case "float":
      return out("double precision");
    case "real":
      return out("real");
    case "date":
      return out("date");
    case "time": {
      const { p, review } = tsPrecision(col);
      return out(withP("time", p), review);
    }
    case "datetime":
    case "smalldatetime":
      return out(
        "timestamp",
        "SQL Server DATETIME has no time zone → timestamp (without tz); pin the source session tz when interpreting values",
      );
    case "datetime2": {
      const { p, review } = tsPrecision(col);
      return out(
        withP("timestamp", p),
        review ?? "DATETIME2 → timestamp (without tz); pin the source session tz",
      );
    }
    case "datetimeoffset": {
      const { p, review } = tsPrecision(col);
      return out(withP("timestamptz", p), review);
    }
    case "char":
    case "nchar":
      return out(`char(${maxLen > 0 ? maxLen : 1})`);
    case "varchar":
    case "nvarchar":
      return maxLen === -1 ? out("text") : out(`varchar(${maxLen > 0 ? maxLen : 255})`);
    case "text":
    case "ntext":
      return out("text");
    case "binary":
    case "varbinary":
    case "image":
      return out("bytea");
    case "uniqueidentifier":
      return out("uuid");
    case "xml":
      return out("xml", "XML → xml; map to text instead if the target lacks XML handling");
    case "timestamp":
    case "rowversion":
      return out(
        "bytea",
        "SQL Server TIMESTAMP/ROWVERSION is an 8-byte binary row-version stamp, NOT a datetime — " +
          "mapped to bytea; it is auto-generated, so usually DROP it on the target instead",
      );
    case "hierarchyid":
      return out("text", "HIERARCHYID → text; no clean Postgres equivalent (design decision)");
    case "geography":
      return out("text", "GEOGRAPHY → text (WKT/WKB); use PostGIS geography if available");
    case "geometry":
      return out("text", "GEOMETRY → text (WKT/WKB); use PostGIS geometry if available");
    case "sql_variant":
      return out("text", "SQL_VARIANT → text; no clean Postgres equivalent (design decision)");
    default:
      return out("text", `unmapped SQL Server type '${dt}'→text — REVIEW`);
  }
}

/**
 * Draft the target Postgres schema for the given SQL Server `schema.tables` by reading the catalog.
 * NEVER applies it — the caller writes it for review and gates cutover on sign-off
 * (GUIDED-MIGRATION.md §7b). `schema`/`tables` are config-validated bare idents. Rows land under
 * `public.<table>` on the target (Debezium's RegexRouter strips the schema), so the draft renders
 * `public.<table>` regardless of the source schema.
 */
export async function draftTargetSchemaSqlServer(
  ss: SqlServerConn,
  schema: string,
  tables: string[],
): Promise<SchemaDraft> {
  const drafts: TableDraft[] = [];
  for (const table of tables) {
    const oid = `OBJECT_ID(QUOTENAME('${schema}') + '.' + QUOTENAME('${table}'))`;
    const cols = await ss.query<SqlServerColumn>(
      `SELECT c.COLUMN_NAME, c.DATA_TYPE, c.IS_NULLABLE, c.CHARACTER_MAXIMUM_LENGTH,
              c.NUMERIC_PRECISION, c.NUMERIC_SCALE, c.DATETIME_PRECISION,
              COLUMNPROPERTY(${oid}, c.COLUMN_NAME, 'IsIdentity') AS IS_IDENTITY,
              COLUMNPROPERTY(${oid}, c.COLUMN_NAME, 'IsComputed') AS IS_COMPUTED
       FROM INFORMATION_SCHEMA.COLUMNS c
       WHERE c.TABLE_SCHEMA = '${schema}' AND c.TABLE_NAME = '${table}'
       ORDER BY c.ORDINAL_POSITION`,
    );
    if (cols.length === 0) {
      throw new Error(
        `sqlserver schema-translate: ${schema}.${table} has no columns — does the table exist?`,
      );
    }
    const pk = await ss.query<{ COLUMN_NAME: string }>(
      `SELECT kcu.COLUMN_NAME
       FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
       JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
         ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
       WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'
         AND tc.TABLE_SCHEMA = '${schema}' AND tc.TABLE_NAME = '${table}'
       ORDER BY kcu.ORDINAL_POSITION`,
    );
    drafts.push(
      renderCreateTableFromColumns(
        table,
        cols.map(translateColumn),
        pk.map((r) => r.COLUMN_NAME),
      ),
    );
  }
  return {
    sql: drafts.map((d) => d.sql).join("\n\n"),
    decisions: drafts.flatMap((d) => d.decisions),
  };
}
